language: node_js
node_js: node
script:
    - npm run lint
    - npm run build
    - npm run export
    - npm test
    - test -f web-ext-artifacts/gecko_code_coverage-*.zip

- name: 1Password Secrets
  uses: RobotsAndPencils/1password-action@v1.1
